replicaCount: 1

myapp_deployment:
  image:
    repository: destian1995/nginx-app
    tag: 1.0.0
  resources:
    requests: 
      memory: "24Mi"
      cpu: "32m"
    limits:
      memory: "48Mi"
      cpu: "64m"
  replicaCount: 5

myapp_service:
  nodeport: 30080
